//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KimballEmailApp.Service.KEIMasterDir {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kess.keint.com/webservices", ConfigurationName="Service.KEIMasterDir.DIR_ServiceSoap")]
    public interface DIR_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Userid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPerson Req_By_Userid(string Userid, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Userid", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPerson> Req_By_UseridAsync(string Userid, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_GUID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPerson Req_By_GUID(string ObjectGUID, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_GUID", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPerson> Req_By_GUIDAsync(string ObjectGUID, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Emplid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPerson Req_By_Emplid(string Emplid, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Emplid", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPerson> Req_By_EmplidAsync(string Emplid, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_UserType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_UserType(string UserType, string All_Info_Boolean, string CreateDate, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_UserType", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_UserTypeAsync(string UserType, string All_Info_Boolean, string CreateDate, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_CostCenter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_CostCenter(string Dept, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_CostCenter", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_CostCenterAsync(string Dept, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Phone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_Phone(string Phone, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Phone", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_PhoneAsync(string Phone, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Name", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_Name(string Name, string All_Info_Boolean, string strPrivate_Numbers, string Location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Name", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_NameAsync(string Name, string All_Info_Boolean, string strPrivate_Numbers, string Location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Common_Name", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_Common_Name(string Common_Name, string All_Info_Boolean, string strPrivate_Numbers, string strBUName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Common_Name", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_Common_NameAsync(string Common_Name, string All_Info_Boolean, string strPrivate_Numbers, string strBUName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Location", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_Location(string strName, string Location, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Location", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_LocationAsync(string strName, string Location, string All_Info_Boolean, string strPrivate_Numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Name_All_People", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_Name_All_People(string Name, string All_Info_Boolean, string strPrivate_Numbers, string Only_Active_Boolean);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_By_Name_All_People", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_Name_All_PeopleAsync(string Name, string All_Info_Boolean, string strPrivate_Numbers, string Only_Active_Boolean);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Mailcodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Mailcodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Mailcodes", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> MailcodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Business_Units", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPeople Business_Units();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Business_Units", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Business_UnitsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Get_Group_Membership", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.GroupMembers[] Get_Group_Membership(string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Get_Group_Membership", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.GroupMembers[]> Get_Group_MembershipAsync(string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_Toplevel_Groups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Req_Toplevel_Groups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Req_Toplevel_Groups", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> Req_Toplevel_GroupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Reload_SQL_Toplevel_Groups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Reload_SQL_Toplevel_Groups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Reload_SQL_Toplevel_Groups", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> Reload_SQL_Toplevel_GroupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/GroupRole_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcPerson GroupRole_Info(string GroupRoleID, string All_Info_Boolean);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/GroupRole_Info", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPerson> GroupRole_InfoAsync(string GroupRoleID, string All_Info_Boolean);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Employee_Photo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KimballEmailApp.Service.KEIMasterDir.strcEmployeePhoto Employee_Photo(string Userid, string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kess.keint.com/webservices/Employee_Photo", ReplyAction="*")]
        System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcEmployeePhoto> Employee_PhotoAsync(string Userid, string EmployeeID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kess.keint.com/webservices")]
    public partial class strcPerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strNameField;
        
        private string strGuidField;
        
        private string strUseridField;
        
        private strcProperty[] strcPropertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string strName {
            get {
                return this.strNameField;
            }
            set {
                this.strNameField = value;
                this.RaisePropertyChanged("strName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strGuid {
            get {
                return this.strGuidField;
            }
            set {
                this.strGuidField = value;
                this.RaisePropertyChanged("strGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string strUserid {
            get {
                return this.strUseridField;
            }
            set {
                this.strUseridField = value;
                this.RaisePropertyChanged("strUserid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public strcProperty[] strcProperties {
            get {
                return this.strcPropertiesField;
            }
            set {
                this.strcPropertiesField = value;
                this.RaisePropertyChanged("strcProperties");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kess.keint.com/webservices")]
    public partial class strcProperty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strPropertyNameField;
        
        private string[] strPropertyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string strPropertyName {
            get {
                return this.strPropertyNameField;
            }
            set {
                this.strPropertyNameField = value;
                this.RaisePropertyChanged("strPropertyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] strPropertyValues {
            get {
                return this.strPropertyValuesField;
            }
            set {
                this.strPropertyValuesField = value;
                this.RaisePropertyChanged("strPropertyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kess.keint.com/webservices")]
    public partial class strcEmployeePhoto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strUseridField;
        
        private string strEmployeeIDField;
        
        private string bolPhotoFoundField;
        
        private byte[] byteEmployeePicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string strUserid {
            get {
                return this.strUseridField;
            }
            set {
                this.strUseridField = value;
                this.RaisePropertyChanged("strUserid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strEmployeeID {
            get {
                return this.strEmployeeIDField;
            }
            set {
                this.strEmployeeIDField = value;
                this.RaisePropertyChanged("strEmployeeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string bolPhotoFound {
            get {
                return this.bolPhotoFoundField;
            }
            set {
                this.bolPhotoFoundField = value;
                this.RaisePropertyChanged("bolPhotoFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] byteEmployeePic {
            get {
                return this.byteEmployeePicField;
            }
            set {
                this.byteEmployeePicField = value;
                this.RaisePropertyChanged("byteEmployeePic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kess.keint.com/webservices")]
    public partial class GroupMembers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strUseridField;
        
        private string strNameField;
        
        private string strGuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string strUserid {
            get {
                return this.strUseridField;
            }
            set {
                this.strUseridField = value;
                this.RaisePropertyChanged("strUserid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strName {
            get {
                return this.strNameField;
            }
            set {
                this.strNameField = value;
                this.RaisePropertyChanged("strName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string strGuid {
            get {
                return this.strGuidField;
            }
            set {
                this.strGuidField = value;
                this.RaisePropertyChanged("strGuid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kess.keint.com/webservices")]
    public partial class strcPeople : object, System.ComponentModel.INotifyPropertyChanged {
        
        private strcPerson[] strcPeopleInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public strcPerson[] strcPeopleInfo {
            get {
                return this.strcPeopleInfoField;
            }
            set {
                this.strcPeopleInfoField = value;
                this.RaisePropertyChanged("strcPeopleInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DIR_ServiceSoapChannel : KimballEmailApp.Service.KEIMasterDir.DIR_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DIR_ServiceSoapClient : System.ServiceModel.ClientBase<KimballEmailApp.Service.KEIMasterDir.DIR_ServiceSoap>, KimballEmailApp.Service.KEIMasterDir.DIR_ServiceSoap {
        
        public DIR_ServiceSoapClient() {
        }
        
        public DIR_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DIR_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DIR_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DIR_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPerson Req_By_Userid(string Userid, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_Userid(Userid, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPerson> Req_By_UseridAsync(string Userid, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_UseridAsync(Userid, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPerson Req_By_GUID(string ObjectGUID, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_GUID(ObjectGUID, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPerson> Req_By_GUIDAsync(string ObjectGUID, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_GUIDAsync(ObjectGUID, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPerson Req_By_Emplid(string Emplid, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_Emplid(Emplid, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPerson> Req_By_EmplidAsync(string Emplid, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_EmplidAsync(Emplid, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_UserType(string UserType, string All_Info_Boolean, string CreateDate, string strPrivate_Numbers) {
            return base.Channel.Req_By_UserType(UserType, All_Info_Boolean, CreateDate, strPrivate_Numbers);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_UserTypeAsync(string UserType, string All_Info_Boolean, string CreateDate, string strPrivate_Numbers) {
            return base.Channel.Req_By_UserTypeAsync(UserType, All_Info_Boolean, CreateDate, strPrivate_Numbers);
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_CostCenter(string Dept, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_CostCenter(Dept, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_CostCenterAsync(string Dept, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_CostCenterAsync(Dept, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_Phone(string Phone, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_Phone(Phone, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_PhoneAsync(string Phone, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_PhoneAsync(Phone, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_Name(string Name, string All_Info_Boolean, string strPrivate_Numbers, string Location) {
            return base.Channel.Req_By_Name(Name, All_Info_Boolean, strPrivate_Numbers, Location);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_NameAsync(string Name, string All_Info_Boolean, string strPrivate_Numbers, string Location) {
            return base.Channel.Req_By_NameAsync(Name, All_Info_Boolean, strPrivate_Numbers, Location);
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_Common_Name(string Common_Name, string All_Info_Boolean, string strPrivate_Numbers, string strBUName) {
            return base.Channel.Req_By_Common_Name(Common_Name, All_Info_Boolean, strPrivate_Numbers, strBUName);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_Common_NameAsync(string Common_Name, string All_Info_Boolean, string strPrivate_Numbers, string strBUName) {
            return base.Channel.Req_By_Common_NameAsync(Common_Name, All_Info_Boolean, strPrivate_Numbers, strBUName);
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_Location(string strName, string Location, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_Location(strName, Location, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_LocationAsync(string strName, string Location, string All_Info_Boolean, string strPrivate_Numbers) {
            return base.Channel.Req_By_LocationAsync(strName, Location, All_Info_Boolean, strPrivate_Numbers);
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPeople Req_By_Name_All_People(string Name, string All_Info_Boolean, string strPrivate_Numbers, string Only_Active_Boolean) {
            return base.Channel.Req_By_Name_All_People(Name, All_Info_Boolean, strPrivate_Numbers, Only_Active_Boolean);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Req_By_Name_All_PeopleAsync(string Name, string All_Info_Boolean, string strPrivate_Numbers, string Only_Active_Boolean) {
            return base.Channel.Req_By_Name_All_PeopleAsync(Name, All_Info_Boolean, strPrivate_Numbers, Only_Active_Boolean);
        }
        
        public string[] Mailcodes() {
            return base.Channel.Mailcodes();
        }
        
        public System.Threading.Tasks.Task<string[]> MailcodesAsync() {
            return base.Channel.MailcodesAsync();
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPeople Business_Units() {
            return base.Channel.Business_Units();
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPeople> Business_UnitsAsync() {
            return base.Channel.Business_UnitsAsync();
        }
        
        public KimballEmailApp.Service.KEIMasterDir.GroupMembers[] Get_Group_Membership(string GroupName) {
            return base.Channel.Get_Group_Membership(GroupName);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.GroupMembers[]> Get_Group_MembershipAsync(string GroupName) {
            return base.Channel.Get_Group_MembershipAsync(GroupName);
        }
        
        public string[] Req_Toplevel_Groups() {
            return base.Channel.Req_Toplevel_Groups();
        }
        
        public System.Threading.Tasks.Task<string[]> Req_Toplevel_GroupsAsync() {
            return base.Channel.Req_Toplevel_GroupsAsync();
        }
        
        public string[] Reload_SQL_Toplevel_Groups() {
            return base.Channel.Reload_SQL_Toplevel_Groups();
        }
        
        public System.Threading.Tasks.Task<string[]> Reload_SQL_Toplevel_GroupsAsync() {
            return base.Channel.Reload_SQL_Toplevel_GroupsAsync();
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcPerson GroupRole_Info(string GroupRoleID, string All_Info_Boolean) {
            return base.Channel.GroupRole_Info(GroupRoleID, All_Info_Boolean);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcPerson> GroupRole_InfoAsync(string GroupRoleID, string All_Info_Boolean) {
            return base.Channel.GroupRole_InfoAsync(GroupRoleID, All_Info_Boolean);
        }
        
        public KimballEmailApp.Service.KEIMasterDir.strcEmployeePhoto Employee_Photo(string Userid, string EmployeeID) {
            return base.Channel.Employee_Photo(Userid, EmployeeID);
        }
        
        public System.Threading.Tasks.Task<KimballEmailApp.Service.KEIMasterDir.strcEmployeePhoto> Employee_PhotoAsync(string Userid, string EmployeeID) {
            return base.Channel.Employee_PhotoAsync(Userid, EmployeeID);
        }
    }
}
